In [1]:
!pip install numpy


In [3]:
import numpy as np

## Numpy :

- It is a Python library that provides a multidimensional array.
- NumPy is an open source mathematical and scientific computing library for Python programming tasks.

In [8]:
## To access the numpy libraries we should install it.

!pip install numpy

In [10]:
## to acess numpy import it

import numpy as np

In [12]:
A = np.array([1,2,3])

In [14]:
print(A)

[1 2 3]


- Numpy is Classfied into 3 types :

 
    1) One Dimensional Array.
    2) Two Dimenssional Array.
    3) Three Dimenssional Array.

## One Dimenssional Array :

- The One-dimensional array contains elements only in one dimension.
- One Dimenssional Array deals with only rows.
- A One dimensional array, also known as a 1D array,

In [27]:
A = np.array([7,11])

In [29]:
print(A)

[ 7 11]


In [33]:
h = np.array([100,108])

In [35]:
print(h)

[100 108]


## Two Dimenssional Array :

- A two-dimensional array, also known as a 2D array.
- Two Dimenssional Array deals with  rows and Columns.

In [42]:
a = np.array([[1,2,3],[4,5,6]])

In [44]:
print(a)

[[1 2 3]
 [4 5 6]]


In [64]:
b = np.array([[3,2,1],[6,5,4]])

In [66]:
print(b)

[[3 2 1]
 [6 5 4]]


## Three Dimenssional Array :

- A three-dimensional array, also known as a 3D array.
- And consists of 3d rows,columns and shapes.

In [68]:
d = np.array([[[1,1,1],[2,2,2],[3,3,3]]]) 

In [70]:
print(d)

[[[1 1 1]
  [2 2 2]
  [3 3 3]]]


## Placeholder :

- Placeholder.
   1) Zeros
   2) Ones 

## * Zeros :

- This function is used to replace the matrix values to zeros because it is called as "Zeros".

In [97]:
A = np.zeros([5,2,3])

In [99]:
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [113]:
b= np.zeros([2,5,9])

In [117]:
print(b)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


## * Ones :

In [103]:
A= np.ones([5,2,3])

In [105]:
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [127]:
s = np.ones([2,5,5])

In [129]:
print(s)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


##  Create Evenly Spaced Values :

In [155]:
q= np.arange(11,50,4)

In [157]:
print(q)

[11 15 19 23 27 31 35 39 43 47]


In [159]:
d = np.arange(100,1000,20)

In [161]:
print(d)

[100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440
 460 480 500 520 540 560 580 600 620 640 660 680 700 720 740 760 780 800
 820 840 860 880 900 920 940 960 980]


In [237]:
y = np.arange(1,1000,142)

In [239]:
print(y)

[  1 143 285 427 569 711 853 995]


In [214]:
r = np.arange(10,100,5)

In [216]:
print(r)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


## evenly spaced samples:

In [254]:
k = np.linspace(1,20,40)   #(starting point ,Ending point,how many times it should divide)

In [256]:
print(k)

[ 1.          1.48717949  1.97435897  2.46153846  2.94871795  3.43589744
  3.92307692  4.41025641  4.8974359   5.38461538  5.87179487  6.35897436
  6.84615385  7.33333333  7.82051282  8.30769231  8.79487179  9.28205128
  9.76923077 10.25641026 10.74358974 11.23076923 11.71794872 12.20512821
 12.69230769 13.17948718 13.66666667 14.15384615 14.64102564 15.12820513
 15.61538462 16.1025641  16.58974359 17.07692308 17.56410256 18.05128205
 18.53846154 19.02564103 19.51282051 20.        ]


In [258]:
A = np.linspace(100,1000,10)

In [260]:
print(A)

[ 100.  200.  300.  400.  500.  600.  700.  800.  900. 1000.]


In [9]:
arun = np.linspace(2,150,20)

In [11]:
print(arun)

[  2.           9.78947368  17.57894737  25.36842105  33.15789474
  40.94736842  48.73684211  56.52631579  64.31578947  72.10526316
  79.89473684  87.68421053  95.47368421 103.26315789 111.05263158
 118.84210526 126.63157895 134.42105263 142.21052632 150.        ]


In [3]:
import numpy as np

In [17]:
## creating an array using mannual number

A = np.full((5),10)
print(A)                                                # 1D
print("Number of Dimenssions :",A.ndim)

[10 10 10 10 10]
Number of Dimenssions : 1


In [51]:
A = np.full((2,2),100)
print(A)                                                # 2D
print("Number of Dimenssions :",A.ndim)

[[100 100]
 [100 100]]
Number of Dimenssions : 2


In [55]:
A = np.full((2,5,6),100)
print(A)                                                # 3D
print("Number of Dimenssions :",A.ndim)

[[[100 100 100 100 100 100]
  [100 100 100 100 100 100]
  [100 100 100 100 100 100]
  [100 100 100 100 100 100]
  [100 100 100 100 100 100]]

 [[100 100 100 100 100 100]
  [100 100 100 100 100 100]
  [100 100 100 100 100 100]
  [100 100 100 100 100 100]
  [100 100 100 100 100 100]]]
Number of Dimenssions : 3


In [57]:
A = np.full((2,3,5,6),9)
print(A)                                                # 3D
print("Number of Dimenssions :",A.ndim)

[[[[9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]]

  [[9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]]

  [[9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]]]


 [[[9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]]

  [[9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]]

  [[9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]
   [9 9 9 9 9 9]]]]
Number of Dimenssions : 4


In [82]:
# create an array using identitty matrix 

A = np.eye(10)
print(A)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [102]:
# create an array using random values in decimal
np.random.random((5,10))


array([[0.99049968, 0.2651109 , 0.69999413, 0.15926138, 0.93059644,
        0.49399031, 0.5111504 , 0.36816452, 0.16980205, 0.24036284],
       [0.58016051, 0.86528277, 0.45412371, 0.47148253, 0.87622652,
        0.08809763, 0.80432773, 0.0762615 , 0.27593444, 0.79269589],
       [0.03882797, 0.21624354, 0.92572501, 0.748146  , 0.68825   ,
        0.95808129, 0.08129295, 0.27719011, 0.37150198, 0.94817134],
       [0.80773237, 0.71403165, 0.29548898, 0.34865169, 0.762684  ,
        0.49014519, 0.97057406, 0.38938536, 0.32855495, 0.51050894],
       [0.60794583, 0.16594857, 0.05231201, 0.38220239, 0.43938204,
        0.73312871, 0.59314447, 0.24097287, 0.0308485 , 0.39588762]])

In [138]:
# create an array using random values  in int
np.random.randint(6,30)

22

In [150]:
# Find the Shape of an Array

A=np.array([[[1,2,3,4],
            [11,22,33,44],                           #3d
            [111,222,333,444],
             [11,22,33,44]]])
print(A.shape)

(1, 4, 4)


In [152]:
A=np.array([[1,2,3,4],
            [11,22,33,44]])                #2d
print(A.shape)

(2, 4)


In [170]:
# Find the number of elements in a Array
A=np.array([[[1,2,3,4],
            [11,22,33,44],                           #3d
            [111,222,333,444],
             [11,22,33,44]]])             
print("Number of elements are  :",A.size)

Number of elements are  : 16


In [197]:
# Find the length of an Array

A=np.array([[9,9,9,9,9,9],
            [9,9,9,9,9,9],
            [9,9,9,9,9,9],
            [9,9,9,9,9,9],
            [9,9,9,9,9,9],
            [9,9,9,9,9,9],
            [9,9,9,9,9,9]])
print("Number of rows in array are :",len(A))

Number of rows in array are : 7


## Accessing the  Array Elements

- we can access the elements in array by using indexing method.
- indexing starts from 0th location.

In [211]:
A = np.array([1,2,3,4,5,6])
print(A[3])

4


In [213]:
# Using indexing method we are using arthemati operation

A = np.array([1,2,3,4,5,6])
print(A[3] +A[2]*A[0]+A[4])


12


In [242]:
# Accessing the Elements on the row and column

A = np.array([[1,2,3,4],
              [4,5,6,7],
              [3,2,1,3],
              [7,8,6,2]])

print(A[3,2])
print(A[2,2])
print(A[0,2])

6
1
3


## " DATA TYPES "  in Numpy.

- NumPy has some extra data types.
- NumPy has some extra data types, and refer to data types with one character, like i for integers.


  1) integers--i
  2) boolean--b
  3) float--f
  4) complex float--c
  5) datatime--M
  6) object--O
  7) string--S
  



In [18]:
import numpy as np

In [20]:
# for string
A = np.array([1,2,3,4], dtype = 'S')
print(A)
print(A.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [22]:
# for float
A = np.array([1,2,3,4], dtype = 'f')
print(A)
print(A.dtype)

[1. 2. 3. 4.]
float32


In [28]:
# for integer
A = np.array([1,2,3,4], dtype = 'i')
print(A)
print(A.dtype)

[1 2 3 4]
int32


In [40]:
# change data type from float to integer by using 'i' as a parameter value 

a = np.array([ 1.1, 1.2, 1.3, 1.4, 1.5])

b = a.astype('i')
print(b)

[1 1 1 1 1]


In [49]:
# create data type from integers to boolean.
a = np.array([1,2,3,0,5,-6,-7])
x = a.astype(bool)
print(x)
print(x.dtype)

[ True  True  True False  True  True  True]
bool


In [59]:
# copy Method.
a = np.array([1,2,3,0,5,-6,-7])
x = a.copy()
a[3] = 108
print("Actual one :",x)
print("After changing value :",a)

Actual one : [ 1  2  3  0  5 -6 -7]
After changing value : [  1   2   3 108   5  -6  -7]


In [61]:
# view Method.
a = np.array([1,2,3,5,-7])
x = a.view()
a[3] = 108
print(x)
print(a)

[  1   2   3 108  -7]
[  1   2   3 108  -7]


In [76]:
# to know the Shape 
S = np.array([[1,2,3,4],
              [5,6,7,8]])

print(S.shape)

(2, 4)


## Reshaping arrays.

- Reshaping means changing the shape of an arrey.
- The shape of an array is the number of elements in each dimensions.
- By reshaping we can add or remove dimenssions or change number of elements in each dimansion

In [89]:
# Convert the following 1-D array with 9 Elements into a 2-D array.

a = np.array([1,2,3,4,5,6,7,8,9])
print(a.size)
print("***********************************************")
s = a.reshape(1,9)
print(s)

9
***********************************************
[[1 2 3 4 5 6 7 8 9]]


In [110]:
# Convert the following 1-D array with 12 Elements into a 3-D array.

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

s = a.reshape(2,1,5)
print(s)

12
***********************************************


ValueError: cannot reshape array of size 12 into shape (2,1,5)